/**
 * Terminal colour palettes. Pure data — no DOM, no xterm.
 *
 * Every bundled palette comes from its upstream project under MIT, with the
 * source and licence recorded per entry.
 */

/** 16 ANSI colours plus background, foreground and cursor. */
export interface TerminalTheme {
  readonly id: string
  readonly label: string
  /** Attribution, shown in the settings screen. */
  readonly credit: string
  readonly background: string
  readonly foreground: string
  readonly cursor: string
  readonly selection: string
  readonly black: string
  readonly red: string
  readonly green: string
  readonly yellow: string
  readonly blue: string
  readonly magenta: string
  readonly cyan: string
  readonly white: string
  readonly brightBlack: string
  readonly brightRed: string
  readonly brightGreen: string
  readonly brightYellow: string
  readonly brightBlue: string
  readonly brightMagenta: string
  readonly brightCyan: string
  readonly brightWhite: string
}

/** Default palette, tuned to the app's panel background. */
export const DEFAULT_THEME: TerminalTheme = {
  id: 'termspace',
  label: 'Termspace',
  credit: "The app's default palette",
  background: '#1b1b1b',
  foreground: '#cfcbc4',
  cursor: '#cfcbc4',
  selection: 'rgba(255,255,255,0.14)',
  black: '#3a3733',
  red: '#cf7a6a',
  green: '#8aa872',
  yellow: '#d0a45c',
  blue: '#7a9bbf',
  magenta: '#a988b0',
  cyan: '#79a8a3',
  white: '#cfcbc4',
  brightBlack: '#6a655e',
  brightRed: '#e0907f',
  brightGreen: '#a3c088',
  brightYellow: '#e6bd74',
  brightBlue: '#94b4d6',
  brightMagenta: '#c3a2c8',
  brightCyan: '#93c1bb',
  brightWhite: '#e8e4dc',
}

const ZENBONES_CREDIT = 'Zenbones (MIT) — Michael Chris Lopez'
const DRACULA_CREDIT = 'Dracula (MIT) — Dracula Theme'

/**
 * Bundled palettes, copied from each project's own terminal export.
 *
 * Zenbones family: https://github.com/zenbones-theme/zenbones.nvim (MIT)
 * Dracula:         https://github.com/dracula/dracula-theme (MIT)
 */
export const BUILT_IN_THEMES: readonly TerminalTheme[] = [
  DEFAULT_THEME,
  {
    id: 'kanagawabones',
    label: 'Kanagawabones',
    credit: ZENBONES_CREDIT,
    background: '#1F1F28',
    foreground: '#DDD8BB',
    cursor: '#E6E0C2',
    selection: '#49473E',
    black: '#1F1F28',
    red: '#E46A78',
    green: '#98BC6D',
    yellow: '#E5C283',
    blue: '#7EB3C9',
    magenta: '#957FB8',
    cyan: '#7EB3C9',
    white: '#DDD8BB',
    brightBlack: '#3C3C51',
    brightRed: '#EC818C',
    brightGreen: '#9EC967',
    brightYellow: '#F1C982',
    brightBlue: '#7BC2DF',
    brightMagenta: '#A98FD2',
    brightCyan: '#7BC2DF',
    brightWhite: '#A8A48D',
  },
  {
    id: 'zenbones',
    label: 'Zenbones',
    credit: ZENBONES_CREDIT,
    background: '#1C1917',
    foreground: '#B4BDC3',
    cursor: '#C4CACF',
    selection: '#3D4042',
    black: '#1C1917',
    red: '#DE6E7C',
    green: '#819B69',
    yellow: '#B77E64',
    blue: '#6099C0',
    magenta: '#B279A7',
    cyan: '#66A5AD',
    white: '#B4BDC3',
    brightBlack: '#403833',
    brightRed: '#E8838F',
    brightGreen: '#8BAE68',
    brightYellow: '#D68C67',
    brightBlue: '#61ABDA',
    brightMagenta: '#CF86C1',
    brightCyan: '#65B8C1',
    brightWhite: '#888F94',
  },
  {
    id: 'zenwritten',
    label: 'Zenwritten',
    credit: ZENBONES_CREDIT,
    background: '#191919',
    foreground: '#BBBBBB',
    cursor: '#C9C9C9',
    selection: '#404040',
    black: '#191919',
    red: '#DE6E7C',
    green: '#819B69',
    yellow: '#B77E64',
    blue: '#6099C0',
    magenta: '#B279A7',
    cyan: '#66A5AD',
    white: '#BBBBBB',
    brightBlack: '#3D3839',
    brightRed: '#E8838F',
    brightGreen: '#8BAE68',
    brightYellow: '#D68C67',
    brightBlue: '#61ABDA',
    brightMagenta: '#CF86C1',
    brightCyan: '#65B8C1',
    brightWhite: '#8E8E8E',
  },
  {
    id: 'neobones',
    label: 'Neobones',
    credit: ZENBONES_CREDIT,
    background: '#0F191F',
    foreground: '#C6D5CF',
    cursor: '#CEDDD7',
    selection: '#3A3E3D',
    black: '#0F191F',
    red: '#DE6E7C',
    green: '#90FF6B',
    yellow: '#B77E64',
    blue: '#8190D4',
    magenta: '#B279A7',
    cyan: '#66A5AD',
    white: '#C6D5CF',
    brightBlack: '#263945',
    brightRed: '#E8838F',
    brightGreen: '#A0FF85',
    brightYellow: '#D68C67',
    brightBlue: '#92A0E2',
    brightMagenta: '#CF86C1',
    brightCyan: '#65B8C1',
    brightWhite: '#98A39E',
  },
  {
    id: 'seoulbones',
    label: 'Seoulbones',
    credit: ZENBONES_CREDIT,
    background: '#4B4B4B',
    foreground: '#DDDDDD',
    cursor: '#E2E2E2',
    selection: '#777777',
    black: '#4B4B4B',
    red: '#E388A3',
    green: '#98BD99',
    yellow: '#FFDF9B',
    blue: '#97BDDE',
    magenta: '#A5A6C5',
    cyan: '#6FBDBE',
    white: '#DDDDDD',
    brightBlack: '#6C6465',
    brightRed: '#EB99B1',
    brightGreen: '#8FCD92',
    brightYellow: '#FFE5B3',
    brightBlue: '#A2C8E9',
    brightMagenta: '#B2B3DA',
    brightCyan: '#6BCACB',
    brightWhite: '#A8A8A8',
  },
  {
    id: 'tokyobones',
    label: 'Tokyobones',
    credit: ZENBONES_CREDIT,
    background: '#1A1B26',
    foreground: '#C0CAF5',
    cursor: '#CED6F7',
    selection: '#2C4075',
    black: '#1A1B26',
    red: '#F77890',
    green: '#74DBCB',
    yellow: '#E1B068',
    blue: '#7BA2F7',
    magenta: '#BB9BF7',
    cyan: '#2BC4DE',
    white: '#C0CAF5',
    brightBlack: '#36384D',
    brightRed: '#F98EA0',
    brightGreen: '#6DE5D3',
    brightYellow: '#F2BA64',
    brightBlue: '#90AFFA',
    brightMagenta: '#C6ACFA',
    brightCyan: '#74DBCB',
    brightWhite: '#7E98EB',
  },
  {
    id: 'forestbones',
    label: 'Forestbones',
    credit: ZENBONES_CREDIT,
    background: '#2C343A',
    foreground: '#E7DCC4',
    cursor: '#EBE2CF',
    selection: '#615B51',
    black: '#2C343A',
    red: '#E67C7F',
    green: '#A9C181',
    yellow: '#DDBD7F',
    blue: '#7FBCB4',
    magenta: '#D69AB7',
    cyan: '#83C193',
    white: '#E7DCC4',
    brightBlack: '#45525C',
    brightRed: '#ED9294',
    brightGreen: '#B0CE7B',
    brightYellow: '#EDC77A',
    brightBlue: '#7AC9C0',
    brightMagenta: '#E5A7C4',
    brightCyan: '#7DD093',
    brightWhite: '#B2A790',
  },
  {
    id: 'nordbones',
    label: 'Nordbones',
    credit: ZENBONES_CREDIT,
    background: '#2F3541',
    foreground: '#EBEEF3',
    cursor: '#EEF1F5',
    selection: '#545F70',
    black: '#2F3541',
    red: '#C1616A',
    green: '#A4BE8D',
    yellow: '#CF866F',
    blue: '#8FBCBA',
    magenta: '#B38DAC',
    cyan: '#87BFCE',
    white: '#EBEEF3',
    brightBlack: '#475063',
    brightRed: '#D6787F',
    brightGreen: '#A8CC86',
    brightYellow: '#E09680',
    brightBlue: '#89CAC8',
    brightMagenta: '#CF97C5',
    brightCyan: '#82CCE0',
    brightWhite: '#A5B4CD',
  },
  {
    id: 'duckbones',
    label: 'Duckbones',
    credit: ZENBONES_CREDIT,
    background: '#0E101A',
    foreground: '#EBEFC0',
    cursor: '#EDF2C2',
    selection: '#37382D',
    black: '#0E101A',
    red: '#E03600',
    green: '#5DCD97',
    yellow: '#E39500',
    blue: '#00A3CB',
    magenta: '#795CCC',
    cyan: '#00A3CB',
    white: '#EBEFC0',
    brightBlack: '#2B2F46',
    brightRed: '#FF4821',
    brightGreen: '#58DB9E',
    brightYellow: '#F6A100',
    brightBlue: '#00B4E0',
    brightMagenta: '#B3A1E6',
    brightCyan: '#00B4E0',
    brightWhite: '#B3B692',
  },
  {
    id: 'zenburned',
    label: 'Zenburned',
    credit: ZENBONES_CREDIT,
    background: '#404040',
    foreground: '#F0E4CF',
    cursor: '#F3EADB',
    selection: '#746956',
    black: '#404040',
    red: '#E3716E',
    green: '#819B69',
    yellow: '#B77E64',
    blue: '#6099C0',
    magenta: '#B279A7',
    cyan: '#66A5AD',
    white: '#F0E4CF',
    brightBlack: '#625A5B',
    brightRed: '#EC8685',
    brightGreen: '#8BAE68',
    brightYellow: '#D68C67',
    brightBlue: '#61ABDA',
    brightMagenta: '#CF86C1',
    brightCyan: '#65B8C1',
    brightWhite: '#C0AB86',
  },
  {
    id: 'rosebones',
    label: 'Rosebones',
    credit: ZENBONES_CREDIT,
    background: '#1A1825',
    foreground: '#E1D4D4',
    cursor: '#E7DDDD',
    selection: '#523A39',
    black: '#1A1825',
    red: '#EB7193',
    green: '#317490',
    yellow: '#F6C074',
    blue: '#9CCFD8',
    magenta: '#C4A7E7',
    cyan: '#9CCFD8',
    white: '#E1D4D4',
    brightBlack: '#3A3651',
    brightRed: '#F289A4',
    brightGreen: '#358DAF',
    brightYellow: '#F9CA8E',
    brightBlue: '#94DAE6',
    brightMagenta: '#CEB3EF',
    brightCyan: '#94DAE6',
    brightWhite: '#BF9B99',
  },
  {
    id: 'vimbones',
    label: 'Vimbones',
    credit: ZENBONES_CREDIT,
    background: '#F0F0CA',
    foreground: '#353535',
    cursor: '#353535',
    selection: '#D7D7D7',
    black: '#F0F0CA',
    red: '#A8334C',
    green: '#4F6C31',
    yellow: '#944927',
    blue: '#286486',
    magenta: '#88507D',
    cyan: '#3B8992',
    white: '#353535',
    brightBlack: '#C6C6A3',
    brightRed: '#94253E',
    brightGreen: '#3F5A22',
    brightYellow: '#803D1C',
    brightBlue: '#1D5573',
    brightMagenta: '#7B3B70',
    brightCyan: '#2B747C',
    brightWhite: '#5C5C5C',
  },
  {
    id: 'dracula',
    label: 'Dracula',
    credit: DRACULA_CREDIT,
    background: '#282A36',
    foreground: '#F8F8F2',
    cursor: '#F8F8F2',
    selection: '#44475A',
    black: '#21222C',
    red: '#FF5555',
    green: '#50FA7B',
    yellow: '#F1FA8C',
    blue: '#BD93F9',
    magenta: '#FF79C6',
    cyan: '#8BE9FD',
    white: '#F8F8F2',
    brightBlack: '#6272A4',
    brightRed: '#FF6E6E',
    brightGreen: '#69FF94',
    brightYellow: '#FFFFA5',
    brightBlue: '#D6ACFF',
    brightMagenta: '#FF92DF',
    brightCyan: '#A4FFFF',
    brightWhite: '#FFFFFF',
  },
]

/** Falls back to the default palette so an unknown name can't break startup. */
export function themeById(id: string, extra: readonly TerminalTheme[] = []): TerminalTheme {
  return [...BUILT_IN_THEMES, ...extra].find((t) => t.id === id) ?? DEFAULT_THEME
}
